
####################################################################################
# Generated by Vivado 2018.1 built on 'Wed Apr  4 18:40:38 MDT 2018' by 'xbuild'
# Command Used: write_xdc -force C:/Users/adity/Desktop/WATER/basic_algo64x64/constrs_1.xdc
####################################################################################


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
